settingに色々移行

diff --git a/bin/wakaru b/bin/wakaru
--- a/bin/wakaru
+++ b/bin/wakaru
@@ -1,29 +1,69 @@
 #!/bin/sh
 
-# シェル変数を展開した時値が設定されていないとエラー
 set -u
-
 usage() {
     echo "Usage: `basename $0` [-h] [channel_with_#]"
-    echo "Default channel is #_vg14engineer"
     exit
 }
 
-while getopts :h OPTION
+emptyUsers() {
+    echo "target user is empty. please add user to setting.json" >&2
+    exit 1
+}
+
+emptyChannel() {
+    echo "target channel is not found. please add channel to setting.json" >&2
+    exit 1
+}
+
+userAndIcon() {
+    target=$1
+    username=`cat ${dir}/setting.json|${jq} ".users[${target}].user"|sed -e 's/\"//g'`
+    icon=`cat ${dir}/setting.json|${jq} ".users[${target}].icon"|sed -e 's/\"//g'`
+    echo "${username} ${icon}"
+}
+
+dry_run=0
+target_channel=
+dir=`dirname $0`/..
+jq=${dir}/lib/jq
+
+while getopts :c:dh OPTION
 do
     case $OPTION in
         h)
             usage
         ;;
+        c)
+            target_channel="${OPTARG}"
+        ;;
+        d)
+            dry_run=1
+        ;;
     esac
 done
 
-channel=${1:-"#_vg14engineer"}
-dir=`dirname $0`
-token=`cat ${dir}/../token`
-jq=`which jq`
-size=`cat ${dir}/../usernames.json|jq ".users|length"`
-target=$(($RANDOM % ${size}))
-username=`cat ${dir}/../usernames.json|jq ".users[${target}].user"|sed -e 's/\"//g'`
-icon=`cat ${dir}/../usernames.json|jq ".users[${target}].icon"|sed -e 's/\"//g'`
-curl -F token=${token} -F channel=${channel} -F text="わかる" -F username=${username} -F icon_url=${icon} https://slack.com/api/chat.postMessage
+channel=`cat ${dir}/setting.json|${jq} ".default.channel"|sed -e 's/\"//g'`
+if [ -n "$target_channel" ]; then
+    channel=`cat ${dir}/setting.json|${jq} ".channels[$target_channel]"|sed -e 's/\"//g'`
+fi
+
+if [ $channel = "null" ]; then
+    emptyChannel
+fi
+
+size=`cat ${dir}/setting.json|${jq} ".users|length"`
+if [ ${size} -eq 0 ]; then
+    emptyUsers
+fi
+
+usernameAndIcon=`userAndIcon $(($RANDOM % ${size}))`
+username=`echo $usernameAndIcon |awk '{print $1}'`
+icon=`echo $usernameAndIcon |awk '{print $2}'`
+
+if [ $dry_run -eq 1 ]; then
+    echo curl -F token=`cat ${dir}/token` -F channel=${channel} -F text="わかる" -F username=${username} -F icon_url=${icon} https://slack.com/api/chat.postMessage
+else
+    curl -F token=`cat ${dir}/token` -F channel=${channel} -F text="わかる" -F username=${username} -F icon_url=${icon} https://slack.com/api/chat.postMessage >> ${dir}/logs/`date "+%Y_%m_%d_%H_%M"`.log
+fi
+
